org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+OptimizeStringConcat
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
android.enableR8.fullMode=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.r8.strictFullModeForKeepRules=false
android.suppressUnsupportedCompileSdk=37.0