[versions]
agp = "9.0.0"
androidx-core = "1.18.0"
androidx-appcompat = "1.7.1"
androidx-leanback = "1.2.0"
androidx-tvprovider = "1.1.0"
androidx-constraintlayout = "2.2.1"
material = "1.14.0"
androidx-lifecycle = "2.10.0"
androidx-fragment = "1.8.9"
androidx-recyclerview = "1.4.0"
androidx-cardview = "1.0.0"
androidx-media3 = "1.10.1"
firebase-bom = "34.14.1"
google-services = "4.4.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "androidx-leanback" }
androidx-leanback-preference = { group = "androidx.leanback", name = "leanback-preference", version.ref = "androidx-leanback" }
androidx-tvprovider = { group = "androidx.tvprovider", name = "tvprovider", version.ref = "androidx-tvprovider" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidx-lifecycle" }
androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "androidx-fragment" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidx-cardview" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "androidx-media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "androidx-media3" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.7" }

